//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Produtos = new HashSet<Produto>();
        }
    
        public int Id { get; set; }
        public int IdDono { get; set; }
        public string Nome { get; set; }
        public int IdRaca { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Cor { get; set; }
        public string Sexo { get; set; }
        public string Observacoes { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Raca Raca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produto> Produtos { get; set; }
    }
}
