//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especificacao
    {
        public int Id { get; set; }
        public int IdProduto { get; set; }
        public string Nome { get; set; }
        public string Valor { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
