//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto_Empresa()
        {
            this.Compra_Produto_Empresa = new HashSet<Compra_Produto_Empresa>();
        }
    
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int IdProduto { get; set; }
        public decimal Valor { get; set; }
        public decimal Estoque { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_Produto_Empresa> Compra_Produto_Empresa { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
