//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Especificacaos = new HashSet<Especificacao>();
            this.Produto_Empresa = new HashSet<Produto_Empresa>();
        }
    
        public int Id { get; set; }
        public int IdCategoria { get; set; }
        public int IdFabricante { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> IdAnimal { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Especificacao> Especificacaos { get; set; }
        public virtual Fabricante Fabricante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produto_Empresa> Produto_Empresa { get; set; }
    }
}
